version: '3.8'

services:
  adk-agent:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
      - GCP_PROJECT_ID=gen-lang-client-0741140892
      - GCP_LOCATION=us-central1
      # - VERTEX_SEARCH_DATA_STORE_ID=your-id
    volumes:
      - ./key.json:/app/key.json
    restart: unless-stopped
